### ISSUE TITLE
Trained with BDD dataset or COCO?

### ISSUE THREAD

**Issue by TheIllusion** [zhanghanduo/yolo3_pytorch#7]
Hi, I'm impressed by this repo and  I'm using the pretrained models with joy. 

However, I'm wondering if the pretrained models are trained with BDD or COCO. 

Could you give me an answer?

**Comment by zhanghanduo** [comment]
Hi. I didn't provide the pretrained models with BDD. It is still COCO. This repo was was developed on top of another popular repo and I simply did some changes. When I was training with BDD, I met some issues and the accuracy was not satisfactory. Then I was busy doing something else and you see I stopped updating code a long time ago. Sorry if this cannot help you.

Currently there are many new state-of-the-art object detection worth trying instead of YOLOv3. I recommend centernet. Good luck.

**Comment by TheIllusion** [comment]
Thanks for the reply.
